#!/bin/bash

# (C)Copyright 2017 Smithee,Spelvin,Agnew & Plinge, Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


echo Content-type: text/html
echo
echo "<HTML><HEAD><TITLE>OSDP Configuration Details</TITLE></HEAD><BODY>"
echo "<PRE>"
echo
echo "CP Configuration (/opt/open-osdp/run/CP/open-osdp-params.json):"
cat /opt/open-osdp/run/CP/open-osdp-params.json
echo "PD Configuration (/opt/open-osdp/run/PD/open-osdp-params.json):"
cat /opt/open-osdp/run/PD/open-osdp-params.json
echo "MON Configuration (/opt/open-osdp/run/MON/open-osdp-params.json):"
cat /opt/open-osdp/run/MON/open-osdp-params.json
echo
echo "<PRE>"
echo "</BODY></HTML>"


